### ISSUE TITLE
Warnings trigged by loading multiple modules

### ISSUE THREAD

**Issue by roife** [SavchenkoValeriy/emacs-swift-module#16]
Thanks for the great package. I have used it developing multiple dynamic modules. However, when I loading the modules constructed with `emacs-swift-module`, it throws warning as the following:

```
objc[49686]: Class _TtC16EmacsSwiftModule9LazyHook0 is implemented in both libEMT.dylib (0x12a405080) and libmacime.dylib (0x129ba6f78).

One of the two will be used. Which one is undefined.
```

I guess it is because the symbol name within two modules are duplicated. And I want to know how to solve the warning.

**Comment by SavchenkoValeriy** [comment]
Thanks for the feedback. That's something that I didn't even check before. I'll look into it!

**Comment by roife** [comment]
This situation only occurs when loading multiple libraries written using Swift dynamic module.

**Comment by roife** [comment]
Wow, this solution sounds very reasonable!

**Comment by citrus-lemon** [comment]
I am sorry. I did not reproduce this issue. I tried to load two modules with using `emacs-swift-module` and my emacs works well as usual.

I am on Emacs "GNU Emacs 29.1 (build 1, aarch64-apple-darwin23.1.0, NS appkit-2487.20 Version 14.1 (Build 23B74))
 of 2023-11-05"
 
Can we have an experiment to verify this issue?

**Comment by SavchenkoValeriy** [comment]
@citrus-lemon I was able to reproduce it. Make sure you launch Emacs from shell to see the output there.

**Comment by SavchenkoValeriy** [comment]
The issue should be fixed now. I didn't add an automated test though (which I should in time), but it requires some refactoring of how I do tests.

**Comment by SavchenkoValeriy** [comment]
The issue should be fixed now. I didn't add an automated test though (which I should in time), but it requires some refactoring of how I do tests.
